### PR TITLE
Update Buried_Water_Potentials.py

### PR DESCRIPTION
**Pull request by davidwych**
Take a look at the changes here, and let me know if they match with your suggested format. I'm working on the README right now as well, and will have the full data file, analysis/plotting script and the image of the data plot uploaded shortly.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Looks good to me! You'll have to update the script that uses this function, of course, then we can merge this, @davidwych .

**Review by davidlmobley — APPROVED** [review]
LGTM.

**Comment by davidlmobley** [comment]
Ah, looks like since this doesn't touch anything your other PR touched, there is no need to update this one to merge, @davidwych .

Do note that you should still fix the function that calls the function renamed here so this PR doesn't break the whole machinery.

**Comment by davidlmobley** [comment]
@davidwych - I think this still needs a fix so we can merge and finalize this.

**Comment by davidlmobley** [comment]
Just to confirm, did you fix the name of the function as noted above?

**Comment by davidwych** [comment]
Yes — it’s called `OutputPotentialData`

David Wych
UC Irvine — Pharmaceutical Sciences
(973)-524-4324

**Pull request merged**
